apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mysqldbDatabase: {{ .Values.mysql.auth.database | b64enc | quote }}
  mysqldbPassword: {{ .Values.mysql.auth.password | b64enc | quote }}
  mysqldbUser: {{ .Values.mysql.auth.username | b64enc | quote }}
  mysqldbRootPassword: {{ .Values.mysql.auth.rootPassword| b64enc | quote }}
